import { Inspection } from "../interfaces/inspections.interface";

export const INSPECTIONS_MOCK: Inspection[] = [
  {
    id: 1,
    date: '2026-01-27 10:14',
    type: 'TALLER MANTENIMIENTO',
    description: 'Mantenimiento sencillo de frenos',
    unit: 'TT450',
    plate: 'EN6318',
    quota: 'RI15705',
    user: 'ABDIEL NIETO',
    owner: 'TOTAL TAXI 2',
    status: 'FINALIZADO',
  },
  {
    id: 2,
    date: '2026-01-27 10:11',
    type: 'TALLER MANTENIMIENTO',
    description: 'Revisión general de aceite',
    unit: 'TT450',
    plate: 'EN6318',
    quota: 'RI15705',
    user: 'ABDIEL NIETO',
    owner: 'TOTAL TAXI 2',
    status: 'PENDIENTE',
  },
  {
    id: 3,
    date: '2026-01-26 15:57',
    type: 'DEVOLUCIÓN VEHÍCULO',
    description: 'Se devuelve a su conductor, la pipa, gato, triángulo.',
    unit: 'UBT1084',
    plate: 'EG6826',
    quota: '8RI11294',
    user: 'YOLANDA RODRIGUEZ',
    owner: 'UNBATTP S.A',
    status: 'FINALIZADO',
  },
  {
    id: 4,
    date: '2026-01-26 10:43',
    type: 'TALLER MANTENIMIENTO',
    description: 'Mantenimiento correctivo motor',
    unit: 'MA39',
    plate: 'EN6311',
    quota: '13T3066',
    user: 'YOLANDA RODRIGUEZ',
    owner: 'MONELOS 147 S.A.',
    status: 'SUSPENDIDO',
  },
  {
    id: 5,
    date: '2026-01-26 15:02',
    type: 'CHAPISTERIA ENTRADA',
    description: 'GOLPE EN LA TAPA DEL MALETERO',
    unit: 'SH24',
    plate: 'EL4062',
    quota: 'RI15901',
    user: 'HECTOR HERNANDEZ',
    owner: 'TRANS. SHEKINAH',
    status: 'FINALIZADO',
  },
  {
    id: 1,
    date: '2026-01-27 10:14',
    type: 'TALLER MANTENIMIENTO',
    description: 'Mantenimiento sencillo de frenos',
    unit: 'TT450',
    plate: 'EN6318',
    quota: 'RI15705',
    user: 'ABDIEL NIETO',
    owner: 'TOTAL TAXI 2',
    status: 'FINALIZADO',
  },
  {
    id: 2,
    date: '2026-01-27 10:11',
    type: 'TALLER MANTENIMIENTO',
    description: 'Revisión general de aceite',
    unit: 'TT450',
    plate: 'EN6318',
    quota: 'RI15705',
    user: 'ABDIEL NIETO',
    owner: 'TOTAL TAXI 2',
    status: 'PENDIENTE',
  },
  {
    id: 3,
    date: '2026-01-26 15:57',
    type: 'DEVOLUCIÓN VEHÍCULO',
    description: 'Se devuelve a su conductor, la pipa, gato, triángulo.',
    unit: 'UBT1084',
    plate: 'EG6826',
    quota: '8RI11294',
    user: 'YOLANDA RODRIGUEZ',
    owner: 'UNBATTP S.A',
    status: 'FINALIZADO',
  },
  {
    id: 4,
    date: '2026-01-26 10:43',
    type: 'TALLER MANTENIMIENTO',
    description: 'Mantenimiento correctivo motor',
    unit: 'MA39',
    plate: 'EN6311',
    quota: '13T3066',
    user: 'YOLANDA RODRIGUEZ',
    owner: 'MONELOS 147 S.A.',
    status: 'SUSPENDIDO',
  },
  {
    id: 5,
    date: '2026-01-26 15:02',
    type: 'CHAPISTERIA ENTRADA',
    description: 'GOLPE EN LA TAPA DEL MALETERO',
    unit: 'SH24',
    plate: 'EL4062',
    quota: 'RI15901',
    user: 'HECTOR HERNANDEZ',
    owner: 'TRANS. SHEKINAH',
    status: 'FINALIZADO',
  },
  {
    id: 1,
    date: '2026-01-27 10:14',
    type: 'TALLER MANTENIMIENTO',
    description: 'Mantenimiento sencillo de frenos',
    unit: 'TT450',
    plate: 'EN6318',
    quota: 'RI15705',
    user: 'ABDIEL NIETO',
    owner: 'TOTAL TAXI 2',
    status: 'FINALIZADO',
  },
  {
    id: 2,
    date: '2026-01-27 10:11',
    type: 'TALLER MANTENIMIENTO',
    description: 'Revisión general de aceite',
    unit: 'TT450',
    plate: 'EN6318',
    quota: 'RI15705',
    user: 'ABDIEL NIETO',
    owner: 'TOTAL TAXI 2',
    status: 'PENDIENTE',
  },
  {
    id: 3,
    date: '2026-01-26 15:57',
    type: 'DEVOLUCIÓN VEHÍCULO',
    description: 'Se devuelve a su conductor, la pipa, gato, triángulo.',
    unit: 'UBT1084',
    plate: 'EG6826',
    quota: '8RI11294',
    user: 'YOLANDA RODRIGUEZ',
    owner: 'UNBATTP S.A',
    status: 'FINALIZADO',
  },
  {
    id: 4,
    date: '2026-01-26 10:43',
    type: 'TALLER MANTENIMIENTO',
    description: 'Mantenimiento correctivo motor',
    unit: 'MA39',
    plate: 'EN6311',
    quota: '13T3066',
    user: 'YOLANDA RODRIGUEZ',
    owner: 'MONELOS 147 S.A.',
    status: 'SUSPENDIDO',
  },
  {
    id: 5,
    date: '2026-01-26 15:02',
    type: 'CHAPISTERIA ENTRADA',
    description: 'GOLPE EN LA TAPA DEL MALETERO',
    unit: 'SH24',
    plate: 'EL4062',
    quota: 'RI15901',
    user: 'HECTOR HERNANDEZ',
    owner: 'TRANS. SHEKINAH',
    status: 'FINALIZADO',
  },
  {
    id: 1,
    date: '2026-01-27 10:14',
    type: 'TALLER MANTENIMIENTO',
    description: 'Mantenimiento sencillo de frenos',
    unit: 'TT450',
    plate: 'EN6318',
    quota: 'RI15705',
    user: 'ABDIEL NIETO',
    owner: 'TOTAL TAXI 2',
    status: 'FINALIZADO',
  },
  {
    id: 2,
    date: '2026-01-27 10:11',
    type: 'TALLER MANTENIMIENTO',
    description: 'Revisión general de aceite',
    unit: 'TT450',
    plate: 'EN6318',
    quota: 'RI15705',
    user: 'ABDIEL NIETO',
    owner: 'TOTAL TAXI 2',
    status: 'PENDIENTE',
  },
  {
    id: 3,
    date: '2026-01-26 15:57',
    type: 'DEVOLUCIÓN VEHÍCULO',
    description: 'Se devuelve a su conductor, la pipa, gato, triángulo.',
    unit: 'UBT1084',
    plate: 'EG6826',
    quota: '8RI11294',
    user: 'YOLANDA RODRIGUEZ',
    owner: 'UNBATTP S.A',
    status: 'FINALIZADO',
  },
  {
    id: 4,
    date: '2026-01-26 10:43',
    type: 'TALLER MANTENIMIENTO',
    description: 'Mantenimiento correctivo motor',
    unit: 'MA39',
    plate: 'EN6311',
    quota: '13T3066',
    user: 'YOLANDA RODRIGUEZ',
    owner: 'MONELOS 147 S.A.',
    status: 'SUSPENDIDO',
  },
  {
    id: 5,
    date: '2026-01-26 15:02',
    type: 'CHAPISTERIA ENTRADA',
    description: 'GOLPE EN LA TAPA DEL MALETERO',
    unit: 'SH24',
    plate: 'EL4062',
    quota: 'RI15901',
    user: 'HECTOR HERNANDEZ',
    owner: 'TRANS. SHEKINAH',
    status: 'FINALIZADO',
  },
];